[package]
authors = ["Austin Schey <aschey13@gmail.com>"]
description = "Declarative migrations and schema management for SQLite"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "slite"
readme = "README.md"
repository = "https://github.com/aschey/slite"
version = "0.0.1-dev"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi-to-tui = "2"
arc-swap = {version = "1.6.0", optional = true}
atty = {version = "0.2", optional = true}
chrono = {version = "0.4", optional = true}
clap = {version = "4.1.4", features = ["derive"], optional = true}
color-eyre = {version = "0.6.2", optional = true}
confique = {version = "0.2.2", default-features = false, features = ["toml"], optional = true}
crossterm = {version = "0.25", optional = true}
futures = {version = "0.3.26", optional = true}
ignore = {version = "0.4.20", optional = true}
imara-diff = {version = "0.1", optional = true}
minus = {version = "5.1.0", features = ["dynamic_output"], optional = true}
notify = {version = "5.1.0", default_features = false, features = ["macos_fsevent"], optional = true}
notify-debouncer-mini = {version = "0.2.1", default_features = false, optional = true}
once_cell = "1"
owo-colors = {version = "3", features = ["supports-colors"], optional = true}
regex = "1"
rusqlite = {version = "0.28", features = ["bundled", "load_extension"]}
serde = {version = "1.0.152", optional = true}
serde_regex = {version = "1.1.0", optional = true}
syntect = {version = "5", default-features = false, features = ["regex-fancy", "parsing"], optional = true}
thiserror = "1"
tokio = {version = "1", features = ["sync", "rt-multi-thread"], optional = true}
tracing = "0.1"
tracing-subscriber = {version = "0.3", optional = true}
tracing-tree2 = {version = "0.3.0", optional = true}
tui = {version = "0.19", optional = true}

[features]
application = [
  "clap",
  "crossterm-events",
  "crossterm/event-stream",
  "diff",
  "pretty-print",
  "read-files",
  "tui",
  "color-eyre",
  "tracing-tree2",
  "notify",
  "notify-debouncer-mini",
  "futures",
  "tokio/macros",
  "serde",
  "serde_regex",
  "confique",
  "arc-swap",
  "minus",
  "atty",
]
crossterm-events = ["crossterm"]
default = ["application"]
diff = ["imara-diff"]
pretty-print = ["owo-colors", "syntect"]
read-files = ["ignore"]
tui = ["dep:tui", "tokio", "tracing-subscriber", "crossterm", "read-files", "chrono"]

[dev-dependencies]
rstest = "0.16.0"
