[config]
default_to_workspace = false

[tasks.update]
args = ["update"]
command = "cargo"
install_crate = "cargo-edit"

[tasks.upgrade]
args = ["upgrade"]
command = "cargo"
install_crate = "cargo-edit"

[tasks.update-all]
dependencies = ["update", "upgrade"]
script = '''
cd util/gen-syntax
makers update-all
'''

[tasks.coverage]
args = ["llvm-cov", "--workspace", "--all-features", "--html", "--open", "--ignore-filename-regex", "\".cargo|.*_test\\.rs\""]
clear = true
command = "cargo"
install_crate = "cargo-llvm-cov"

[tasks.build-release]
args = [
  "+nightly",
  "build",
  "-Z",
  "build-std=std,panic_abort",
  "-Z",
  "build-std-features=panic_immediate_abort",
  "--target",
  "x86_64-unknown-linux-gnu",
  "--release",
]
command = "cargo"
