[package]
edition = "2021"
name = "schemalite-cli"
version = "0.1.0"

[[bin]]
doc = false
name = "slite"
path = "src/bin/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.0.32", features = ["derive"]}
schemalite = {path = "../schemalite"}
