after_migration = "./post-migration"
before_migration = "./pre-migration"
extension_dir = "./extensions"
ignore = "(search_spellfix_vocab.*)|(search_index_.*)"
log_level = "debug"
pager = false
source = "./schema"
target = "./demo.db"
